package com.hull.entity.db;


import com.hull.common.base.BaseEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class SysMenu extends BaseEntity {
  /**
  菜单ID
  **/
  private Integer menuId;
  /**
  菜单标题
  **/
  private String menuTitle;
  /**
  菜单编号
  **/
  private Long menuIndex;

  public Integer getMenuId() {
  	return menuId;
  }
	
  public void setMenuId(Integer menuId) {
    this.menuId = menuId;
  }
	
  public String getMenuTitle() {
  	return menuTitle;
  }
	
  public void setMenuTitle(String menuTitle) {
    this.menuTitle = menuTitle;
  }
	
  public Long getMenuIndex() {
  	return menuIndex;
  }
	
  public void setMenuIndex(Long menuIndex) {
    this.menuIndex = menuIndex;
  }
	
}
