package com.hull.entity.db;


import com.hull.common.base.BaseEntity;

/**
WARNING: 
this code is generated by CodeMonkey
please DO NOT modify this file
**/
public class SysUserRole extends BaseEntity {
  private Integer userId;
  private Integer roleId;

  public Integer getUserId() {
  	return userId;
  }
	
  public void setUserId(Integer userId) {
    this.userId = userId;
  }
	
  public Integer getRoleId() {
  	return roleId;
  }
	
  public void setRoleId(Integer roleId) {
    this.roleId = roleId;
  }
	
}
